# Generated by Django 5.0.1 on 2024-01-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_author_id_alter_book_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
    ]
