# Generated by Django 5.0.1 on 2024-01-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_author_name_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
    ]
