# Generated by Django 5.0.1 on 2024-01-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_author_slug_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='slug',
            field=models.SlugField(default='slug', max_length=400),
        ),
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='slug', max_length=400),
        ),
    ]
