# Generated by Django 5.0.1 on 2024-01-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_author_slug_alter_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.ImageField(upload_to=''),
        ),
    ]
