# Generated by Django 5.0.1 on 2024-01-31 17:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_book_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
